---
### Helm Settings

# RKE Settings
rke_config_folder: /home/rke/.kube
rke_cluster_kube_config: "/home/rke/.kube/config"
rke_user: rke
rke_home: /home/rke

# Binary settings
kubectl_binary: /usr/local/bin/kubectl
helm_binary: /usr/local/bin/helm

# Repo settings
helm_certmanager_version: v1.5.1
helm_certmanager_jetstack_repo: jetstack
helm_certmanager_jetstack_repo_url: https://charts.jetstack.io

helm_metallb_version: ""
helm_metallb__repo: bitnami
helm_metallb_repo_url: https://charts.bitnami.com/bitnami
# The IP address ranges are listed in the Helm command for MetalLB
# --set configInline.address-pools[0].addresses={192.168.1.100-192.168.1.250}

helm_ingress_version: ""
helm_ingress_repo: ingress-nginx
helm_ingress_repo_url: https://kubernetes.github.io/ingress-nginx
loadBalancerIP: 192.168.1.101

helm_rancher_repo: rancher-latest
helm_rancher_repo_url: https://releases.rancher.com/server-charts/latest
helm_rancher_version: v2.6.2

# General Rancher Settings
rancher_hostname: "k8s.example.com"
rancher_certmanager_enabled: true
rancher_metallb_enabled: true
rancher_ingress_enabled: true
rancher_rancher_enabled: true

rancher_certmanager_crd_url: "https://github.com/jetstack/cert-manager/releases/download/v1.5.1/cert-manager.crds.yaml"

